worker:
  closeOnStandbyTime: 60000

sensors:
  CCS811:
    address: 0x5a
    bus: 3
    timeout: 2000
  DHT22:
    pin: 4
    timeout: 2000
  MAX44009:
    address: 0x4A
    bus: 1
    timeout: 500
  MAX30102:
    address: 0x57
    bus: 2
    timeout: 1000
  SI1145:
    address: 0x60
    bus: 4
    timeout: 500

display:
  width: 240
  height: 240
  imageSize: 150
  bus: SPI0.0
  dcPin: 25
  backlightPin: 18
  resetPin: 15

gateway:
  connectionConfig: connection.yaml
  identity:
    certificate: ../identity.pem
    privateKey: ../identity.key
    userID: device
    orgID: supplier
    mspID: supplierMSP
  channelID: supply-channel
  walletPath: ../keystore
