device:
  id_file_path: ../device.id
  hotswap_detect_interval: 3s

engine:
  sensor_sleep_standby_timeout: 1m

gateway:
  connection_config: connection.yaml
  identity:
    certificate: ../identity.pem
    private_key: ../identity.key
    user_id: device
    org_id: supplier
    msp_id: supplierMSP
  channel_id: supply-channel
  wallet_path: ../keystore

sensors:
  DHT22:
    pin: 4
    timeout: 2000

display:
  width: 240
  height: 240
  image_size: 150
  bus: SPI0.0
  dc_pin: 25
  backlight_pin: 18
  reset_pin: 15
