device:
  id_file_path: ../device.id
  register_timeout_duration: 1m
  i2c_scan_timeout: 150ms
  hotswap_detect_interval: 3s
  local_cache_path: /var/sensorsys/cache
  ping_timer_interval: 10s
  battery_monitor_bus: 6

engine:
  sensor_sleep_standby_timeout: 1m

gateway:
  connection_config: connection.yaml
  identity:
    certificate: ../identity.pem
    private_key: ../identity.key
    user_id: device
    org_id: supplier
    msp_id: supplierMSP
  channel_id: supply-channel
  wallet_path: ../keystore

bluetooth:
  name: ChainMetric IoT Device
  scan_duration: 1m
  advertise_duration: 1m

sensors:
  analog:
    samples_per_read: 100
  dht22:
    pin: 4

display:
  enabled: true
  width: 128
  height: 250
  bus: SPI0.0
  dc_pin: 25
  cs_pin: 8
  reset_pin: 4
  busy_pin: 22
