device:
  id_file_path: ../device.id
  register_timeout_duration: 1m
  hotswap_detect_interval: 3s
  local_cache_path: /var/sensorsys/cache
  ping_timer_interval: 10s

engine:
  sensor_sleep_standby_timeout: 1m

gateway:
  connection_config: connection.yaml
  identity:
    certificate: ../identity.pem
    private_key: ../identity.key
    user_id: device
    org_id: supplier
    msp_id: supplierMSP
  channel_id: supply-channel
  wallet_path: ../keystore

sensors:
  analog:
    samples_per_read: 100
  dht22:
    pin: 4
    timeout: 2000

display:
  enabled: true
  width: 128
  height: 250
  image_size: 128
  bus: SPI0.0
  dc_pin: 25
  cs_pin: 8
  reset_pin: 22
  busy_pin: 16
