device:
  id_file_path: ../device.id
  register_timeout_duration: 1m
  i2c_scan_timeout: 150ms
  hotswap_detect_interval: 3s
  local_cache_path: /var/sensorsys/cache
  ping_timer_interval: 10s
  assets_locate_distance: 50.0
  battery_check_interval: 1m

engine:
  sensor_sleep_standby_timeout: 1m

blockchain:
  connection_config: connection.yaml
  identity:
    certificate: ../identity.pem
    private_key: ../identity.key
    user_id: device
    org_id: supplier
    msp_id: supplierMSP
  channel_id: supply-channel
  wallet_path: ../keystore

bluetooth:
  enabled: true
  device_name: chainmetric.device
  scan_duration: 1m
  advertise_duration: 1m
  location:
    service_uuid: F8AE4978-5AAB-46C3-A8CB-127F347EAA01

sensors:
  analog:
    samples_per_read: 100

display:
  enabled: true
  width: 128
  height: 250
  bus: SPI0.0
  dc_pin: 25
  cs_pin: 8
  reset_pin: 22
  busy_pin: 18

local_events_buffer_size: 50
