name: Go CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go environment
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...

  go-linter:
    name: Go Linter
    runs-on: ubuntu-latest
    steps:
      - name: go1.13 linter
        uses: shoukoo/golang-pipeline/go1.13/linter@master
        with:
          GOLINT: on
          GOLINTPATH: .
          MISSPELL: off
